apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: ikekz/made:online-inference
      name: fastapi-ml
      ports:
        - containerPort: 8000