apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-ml-replicaset
  labels:
    app: fastapi-ml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      name: fastapi
      labels:
        app: fastapi
    spec:
      containers:
        - image: ikekz/made:online-inference
          name: fastapi-ml
          ports:
            - containerPort: 8000