input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
feature_transformer_path: "models/transformer.pkl"
splitting_params:
  test_size: 0.2
  random_state: 20
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "fbs"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
  target_col: "condition"
training_params:
  model_type: "LogisticRegression"
  random_state: 20
